# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blaise Page (brraaaap)
email: BlaisePageTech@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Blaise Page. I developed this website to 
  make projects of mine public and expand my prfessional network.
  Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  BlaisePage

# Build settings
markdown: kramdown
